//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLA_PRUEBA_EDUCACION
    {
        public long id { get; set; }
        public string coleccion { get; set; }
        public string sector { get; set; }
        public string tema { get; set; }
        public string contenido { get; set; }
        public string pais { get; set; }
        public string escala { get; set; }
        public string territorio { get; set; }
        public string temporalidad { get; set; }
        public string unidad_medida { get; set; }
        public string fuente { get; set; }
        public string titulo { get; set; }
        public string descripcion_larga { get; set; }
        public string visualizacion { get; set; }
        public string tag { get; set; }
        public string url { get; set; }
        public string filtro_url { get; set; }
        public string filtro_integrado { get; set; }
        public string muestra { get; set; }
        public string suscripcion { get; set; }
        public string coleccion_id { get; set; }
    }
}
